version: '3'
services:
  nodejsapp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nodejsapp # Replace with the appropriate Node.js version
    ports:
      - "3000:3000"
    working_dir: /app  # new volume con container
    volumes:
      - ./app:/app    # from repo to /
    command: npm start  # Replace with the start command for your Node.js app